### ISSUE TITLE
Entrevista 

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-8-entrevista-equipo-daniel#1]
Daniel Velasco López
Edgar Mauricio Sarmiento Ruiz
Sandy Marissa García Santiago
Actividad 8.  Entrevista
[Entrevista sobre la web.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-entrevista-equipo-daniel/files/9855478/Entrevista.sobre.la.web.pdf)

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 8 "ENTREVISTA"
DE ACUERDO A LA RUBRICA OBTUVIERON EL ("20%") DEL 20% QUE EQUIVALE LA ACTIVIDAD.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
